export { default as Loader } from "./Loader"
export { default as Footer } from "./Footer"
export { default as Navbar } from "./Navbar"
export { default as Services } from "./Services"
export { default as Transcation } from "./Transcation"
export { default as Welcom } from "./Welcom"